### ISSUE TITLE
Using fusepy get error on windows10

### ISSUE THREAD

**Issue by Pagliacii** [billziss-gh/fusepy#3]
Hey, why should i always get this error on windows?
Traceback (most recent call last):
  File "build\bdist.win-amd64\egg\fuse.py", line 554, in _wrapper
    return func(*args, **kwargs) or 0
  File "build\bdist.win-amd64\egg\fuse.py", line 668, in statfs
    for key, val in attrs.items():
AttributeError: 'NoneType' object has no attribute 'items'

**Comment by billziss-gh** [comment]
Are you returning a properly constructed `dict` from `statfs` as here?

https://github.com/billziss-gh/fusepy/blob/master/examples/memory.py#L107-L108

**Comment by Pagliacii** [comment]
oh!thanks!It can work now

**Comment by billziss-gh** [comment]
Glad to be of help.

**Comment by Pagliacii** [comment]
Can i run loopback.py on windows?
If not, what should i do can make it work?

**Comment by billziss-gh** [comment]
I am not sure if I have tried it. Does it not work if you try to run it?

**Comment by Pagliacii** [comment]
Well, when i'm trying to run loopback.py on windows, i get something AttributeError such as:
'module' object has no attribute 'statvfs', 'chown', 'mknod', 'readlink'.
So i just remove them and rewrite the open method, now the script can work.
But there are some bugs,and now I want to list one of them:
when i use 'mkdir' command to create a folder, the loopback file system can work correctly. But if i use right-click menu to create folder after using Windows Explorer to open mount point , it  will create 4 new folders.

**Comment by billziss-gh** [comment]
This happens when Explorer retries the directory creation because of permission problems.

Return a permission such as 0777 from `getattr` to fix the problem.

**Comment by Pagliacii** [comment]
It still create 4 folders when `getattr` method return a permission
This is my `getattr`:
```python
    def getattr(self, path, fh=None):
        try:
            st = os.lstat(path)
            status = dict(
                (key, getattr(st, key))
                for key in (
                    'st_atime', 'st_ctime', 'st_gid', 'st_mode',
                    'st_mtime', 'st_nlink', 'st_size', 'st_uid',
                )
            )
            if os.path.isdir(path):
                status.update({
                    'st_mode': (S_IFDIR | 0o777),
                })
            else:
                status.update({
                    'st_mode': (S_IFREG | 0o666),
                })
            return status
        except:
            raise FuseOSError(ENOENT)
```

**Comment by billziss-gh** [comment]
Try returning a uid of 65792 (which is the same as "World"). This should give universal access to Everyone.

**Comment by Pagliacii** [comment]
Aha! Creating directory works correctly now! But I cannot open any file except text file.

**Comment by N-Coder** [comment]
This is probably the same problem as in issue #8. @billziss-gh can I be of any help fixing this issue?

**Comment by billziss-gh** [comment]
> @billziss-gh can I be of any help fixing this issue?

You are most welcome to try :) I have had very little time in the last few weeks and I expect this to be the case in the coming weeks as well. (I am working on a new cross-platform file system and most of my time currently goes into it.)

**Comment by N-Coder** [comment]
@Pagliacii try my fix from issue #8 and explicitly set `O_BINARY` in the open function.
